//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systemri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorija_Proizvoda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategorija_Proizvoda()
        {
            this.Proizvods = new HashSet<Proizvod>();
        }
    
        public int ID_kategorije_proizvoda { get; set; }
        public string Naziv_kategorije_proizvoda { get; set; }
        public string Opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proizvod> Proizvods { get; set; }

        public override string ToString()
        {
            return ID_kategorije_proizvoda.ToString() + "-" + Naziv_kategorije_proizvoda;
        }
    }
}
