//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systemri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poduzece
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poduzece()
        {
            this.Podruznicas = new HashSet<Podruznica>();
        }
    
        public int ID_poduzeca { get; set; }
        public string Naziv_poduzeca { get; set; }
        public string Adresa_poduzeca { get; set; }
        public string OIB_poduzeca { get; set; }
        public string Vlasnik_poduzeca { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podruznica> Podruznicas { get; set; }
    }
}
