//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systemri
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvod()
        {
            this.Stavkas = new HashSet<Stavka>();
        }
    
        public int ID_proizvoda { get; set; }
        public string Naziv_proizvoda { get; set; }
        public double Cijena_proizvoda { get; set; }
        public int Kolicina_proizvoda { get; set; }
        public short Popust { get; set; }
        public double Postotak_popusta { get; set; }
        public int Kategorija_proizvoda_ID { get; set; }
        public int Dobavljac_ID { get; set; }
        public int Proizvodac_ID { get; set; }
        public string Mjerna_jedinica_ID { get; set; }
        public int Podruznica_ID { get; set; }
    
        public virtual Dobavljac Dobavljac { get; set; }
        public virtual Kategorija_Proizvoda Kategorija_Proizvoda { get; set; }
        public virtual Mjerna_Jedinica Mjerna_Jedinica { get; set; }
        public virtual Proizvodac Proizvodac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka> Stavkas { get; set; }
        public virtual Podruznica Podruznica { get; set; }
    }
}
