//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Systemri
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemriDBEntities : DbContext
    {
        public SystemriDBEntities()
            : base("name=SystemriDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dobavljac> Dobavljacs { get; set; }
        public virtual DbSet<Kategorija_Proizvoda> Kategorija_Proizvoda { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Mjerna_Jedinica> Mjerna_Jedinica { get; set; }
        public virtual DbSet<Podruznica> Podruznicas { get; set; }
        public virtual DbSet<Poduzece> Poduzeces { get; set; }
        public virtual DbSet<Proizvod> Proizvods { get; set; }
        public virtual DbSet<Proizvodac> Proizvodacs { get; set; }
        public virtual DbSet<Racun> Racuns { get; set; }
        public virtual DbSet<Stavka> Stavkas { get; set; }
        public virtual DbSet<Uloga> Ulogas { get; set; }
    }
}
